from __future__ import annotations

from enum import StrEnum


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class BatchStatus(StrEnum):
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
